### ISSUE TITLE
Attempt to set a screen on a child window.

### ISSUE THREAD

**Issue by dieKoderin** [ros-visualization/rqt_pose_view#1] opened 2017-05-11 07:37 UTC
I try to run it like this:

    rqt --standalone rqt_pose_view

I directly get these error or warnings:

    0x23ff320 void QWindowPrivate::setTopLevelScreen(QScreen*, bool) ( QScreen(0x2aec0b0) ): Attempt     to set a screen on a child window.
    0x23ff810 void QWindowPrivate::setTopLevelScreen(QScreen*, bool) ( QScreen(0x2aec0b0) ): Attempt to set a screen on a child window.
    0x23ffc10 void QWindowPrivate::setTopLevelScreen(QScreen*, bool) ( QScreen(0x2aec0b0) ): Attempt to set a screen on a child window.
    0x23f75a0 void QWindowPrivate::setTopLevelScreen(QScreen*, bool) ( QScreen(0x2aec0b0) ): Attempt to set a screen on a child window.
    0x23ffc10 void QWindowPrivate::setTopLevelScreen(QScreen*, bool) ( QScreen(0x2aec0b0) ): Attempt to set a screen on a child window.
    0x3e34fc0 void QWindowPrivate::setTopLevelScreen(QScreen*, bool) ( QScreen(0x2aec0b0) ): Attempt to set a screen on a child window.
    0x23f75a0 void QWindowPrivate::setTopLevelScreen(QScreen*, bool) ( QScreen(0x2aec0b0) ): Attempt to set a screen on a child window.
    0x24006f0 void QWindowPrivate::setTopLevelScreen(QScreen*, bool) ( QScreen(0x2aec0b0) ): Attempt to set a screen on a child window.

and when I try to drag and drop any topic from:

    rqt --standalone rqt_topic.topic.Topic

I get this error:

    PoseViewWidget.dragEnterEvent(): event.source() has no attribute selectedItems or length of selectedItems is 0

**Comment by dirk-thomas** [comment] 2017-05-22 18:08
I can reproduce the problem. Can you please provide more information, e.g. what platform are you on, what version of `rqt_pose_view`, `rqt_gui`, `qt_gui` and Qt are you using, are you using PyQt or PySide (see about dialog of rqt).

**Comment by dieKoderin** [comment] 2017-05-24 09:07
I am on Ubuntu 16.04.2 LTS.
Python 2.7.12
QMake version 2.01a
Using Qt version 4.8.7

**Comment by dirk-thomas** [comment] 2017-05-24 14:30
ROS Kinetic and Lunar (which are the ROS distros supported on Xenial) only target Qt 5. Have you build the packages from source to use Qt 4?

Can you please provide all the information from the rqt about dialog.

**Comment by dirk-thomas** [comment] 2017-07-18 21:38
I will close this ticket for now since without the missing requested information there is nothing I can act on. Please feel free to comment with more information and this ticket can be reopened.

**Closed as completed by dirk-thomas** 2017-07-18 21:38 UTC
Labels: more-information-needed
